import Head from "next/head";
import { Header } from "@/components/header";
import { FirstSection } from "@/components/firstSection"
import {SecondSection} from "@/components/secondSection";
import {FourthSection} from "@/components/fourthSection";
import {ThirdSection} from "@/components/thirdSection";


export default function Home() {
  return (
    <>
      <Head>
        <title>Lumos - test app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          <Header />
          <FirstSection />
          <SecondSection />
          <ThirdSection />
          <FourthSection />
    </>
  );
}
